version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6667:6667"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: hms
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    build:
      context: ./backend
    command: npx knex migrate:latest
    depends_on:
      - db

volumes:
  db_data:
