version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6667:6667"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # command: >
    #   sh -c "npx knex migrate:latest && npm run start"

  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npx knex migrate:latest
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    environment:
      NODE_ENV: production

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: hms
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
